[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
celery = "^5.5.2"
redis = "^6.1.0"
fastapi = {extras = ["standard"], version = "^0.115.12"}
pydantic-settings = "^2.9.1"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

